# .github/workflows/mirror-to-gitlab.yml
name: Mirror to GitLab
on: [push]
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@git.isir.upmc.fr/scai-formation/2026_medecine_dfgsm2-ia-s2.git
          git push gitlab --all --force
          git push gitlab --tags --force
